server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Prevent caching for Flutter core JavaScript, Service Worker, and HTML files
    location ~* (index\.html|flutter_service_worker\.js|flutter_bootstrap\.js|main\.dart\.js|version\.json)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires 0;
    }

    # Cache images and font assets
    location ~* \.(?:ico|gif|jpe?g|png|woff2?|eot|ttf|svg|css)$ {
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}
