// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYp5pkGVRVZFFTs_MxWEZ2SuhUkqP3L9g',
    appId: '1:679778128088:web:90a70d3201cc2619f707ad',
    messagingSenderId: '679778128088',
    projectId: 'kitchen-maintenance-app',
    authDomain: 'kitchen-maintenance-app.firebaseapp.com',
    storageBucket: 'kitchen-maintenance-app.firebasestorage.app',
    measurementId: 'G-8ZGF1FCM74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALXh3cFppDj7uBhp01F0JipdXBbGpQy_4',
    appId: '1:679778128088:android:c0f640d836c8836bf707ad',
    messagingSenderId: '679778128088',
    projectId: 'kitchen-maintenance-app',
    storageBucket: 'kitchen-maintenance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYVrz6tYd7ZOSo8Po84dzPRa8gyUlqlo',
    appId: '1:679778128088:ios:380e0e6ba0ed21fbf707ad',
    messagingSenderId: '679778128088',
    projectId: 'kitchen-maintenance-app',
    storageBucket: 'kitchen-maintenance-app.firebasestorage.app',
    iosBundleId: 'com.example.kitchenMaintanence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfYVrz6tYd7ZOSo8Po84dzPRa8gyUlqlo',
    appId: '1:679778128088:ios:380e0e6ba0ed21fbf707ad',
    messagingSenderId: '679778128088',
    projectId: 'kitchen-maintenance-app',
    storageBucket: 'kitchen-maintenance-app.firebasestorage.app',
    iosBundleId: 'com.example.kitchenMaintanence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYp5pkGVRVZFFTs_MxWEZ2SuhUkqP3L9g',
    appId: '1:679778128088:web:65bf835e02af4204f707ad',
    messagingSenderId: '679778128088',
    projectId: 'kitchen-maintenance-app',
    authDomain: 'kitchen-maintenance-app.firebaseapp.com',
    storageBucket: 'kitchen-maintenance-app.firebasestorage.app',
    measurementId: 'G-B5NQLYPLP3',
  );
}
